language: python
sudo: false

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=black

    - python: 3.7
      env: TOXENV=docs

    - python: 2.7
      env: TOXENV=py27-codecov

    - python: 3.5
      env: TOXENV=py35-codecov

    - python: 3.6
      env: TOXENV=py36-codecov

    - python: 3.7
      env: TOXENV=py37-codecov

    - python: 3.8
      env: TOXENV=py38-codecov

    - python: pypy
      env: TOXENV=pypy2-codecov

    - python: pypy3
      env: TOXENV=pypy3-codecov


install: pip install tox
script: TOX_SKIP_MISSING_INTERPRETERS="False" tox

deploy:
  - provider: pypi
    user: __token__
    password:
      secure: "C0hRA/TnDOxMQyCUngaoUVp4PGVfPhIeh8Yr6sFa2XN+y0/afJVXBzbz2zrzXflg93zsZIppNTS+sUuYauae/v8ZRqvU1pjS5xVdlZytMBRt53omej2pe+m4DPe8RADIy5fkfuEyt9F1j7ZKXnxwXI+kz1x6cXShM09pCtCuvc26vTNQN3HycUeA11Fp3Bir4CGMx1qKE6hWwzM1+TP2Ci9Vp4mgAh6oqwpfKYIKtbJRd9Uy5r8RPmfc2suaau5S4kCKjqSGvrcbAOjpTTl6TZoTTpJstPnXb46kDwRaAWC34CRrgK3f0dgfyTm2OKgRMCrhR4JiZp016YvcADKySTtQOlyYn+x9jbV4j0USP8yebJLtPrWX124JAy1Y4tnCXsW7E3Uh7yK1pm3DO1WquHgT3qwUcsL6NCaoGCt9NwzunV0jTTRAVr43zpxkBaD73Vejv3gHaLpMrwccqywFZEjjUh0qJLk3qBIAWefV3aKhPoefRqFRN56BZFbcr0KZTCjZfFGUjno6ncblHqNbYd365SC95dt+FOh9GP7gkHX3l+R9F/eGxfyubPrZLrZSn01y0gSQFLEFHIyYzVofq8p0OZN6ZB/lebOE3r3SHrfiUJF5hoGCyCrqERCCiO2fjn8WmR+n1MLTmdafVlMCnm+FMq1d7pcodK8QDjYk6vo="
    on:
      branch: master
      python: 3.7
      condition: $TOXENV = py38-codecov
    distributions: "sdist bdist_wheel"
